# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: commands.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='commands.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0e\x63ommands.proto\"?\n\x07\x43ommand\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04verb\x18\x02 \x01(\t\x12\x0c\n\x04path\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x04 \x01(\t\"\x14\n\x12GetCommandsRequest\".\n\x11GetCommandsResult\x12\x19\n\x07\x63ommand\x18\x01 \x01(\x0b\x32\x08.Command2D\n\x08\x43ommands\x12\x38\n\x0bGetCommands\x12\x13.GetCommandsRequest\x1a\x12.GetCommandsResult0\x01\x62\x06proto3')
)




_COMMAND = _descriptor.Descriptor(
  name='Command',
  full_name='Command',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Command.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='verb', full_name='Command.verb', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='path', full_name='Command.path', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='Command.name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=81,
)


_GETCOMMANDSREQUEST = _descriptor.Descriptor(
  name='GetCommandsRequest',
  full_name='GetCommandsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=103,
)


_GETCOMMANDSRESULT = _descriptor.Descriptor(
  name='GetCommandsResult',
  full_name='GetCommandsResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='GetCommandsResult.command', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=151,
)

_GETCOMMANDSRESULT.fields_by_name['command'].message_type = _COMMAND
DESCRIPTOR.message_types_by_name['Command'] = _COMMAND
DESCRIPTOR.message_types_by_name['GetCommandsRequest'] = _GETCOMMANDSREQUEST
DESCRIPTOR.message_types_by_name['GetCommandsResult'] = _GETCOMMANDSRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Command = _reflection.GeneratedProtocolMessageType('Command', (_message.Message,), dict(
  DESCRIPTOR = _COMMAND,
  __module__ = 'commands_pb2'
  # @@protoc_insertion_point(class_scope:Command)
  ))
_sym_db.RegisterMessage(Command)

GetCommandsRequest = _reflection.GeneratedProtocolMessageType('GetCommandsRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETCOMMANDSREQUEST,
  __module__ = 'commands_pb2'
  # @@protoc_insertion_point(class_scope:GetCommandsRequest)
  ))
_sym_db.RegisterMessage(GetCommandsRequest)

GetCommandsResult = _reflection.GeneratedProtocolMessageType('GetCommandsResult', (_message.Message,), dict(
  DESCRIPTOR = _GETCOMMANDSRESULT,
  __module__ = 'commands_pb2'
  # @@protoc_insertion_point(class_scope:GetCommandsResult)
  ))
_sym_db.RegisterMessage(GetCommandsResult)



_COMMANDS = _descriptor.ServiceDescriptor(
  name='Commands',
  full_name='Commands',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=153,
  serialized_end=221,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetCommands',
    full_name='Commands.GetCommands',
    index=0,
    containing_service=None,
    input_type=_GETCOMMANDSREQUEST,
    output_type=_GETCOMMANDSRESULT,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_COMMANDS)

DESCRIPTOR.services_by_name['Commands'] = _COMMANDS

# @@protoc_insertion_point(module_scope)
